from enum import StrEnum


class SecurityLabel(StrEnum):
    SENSITIVE = "SENSITIVE"
    CREDENTIAL = "CREDENTIAL"
    SECRET = "SECRET"
    PERSONAL = "PERSONAL"
    FINANCIAL = "FINANCIAL"
    INTERNAL_DATA = "INTERNAL_DATA"

    TRUSTED = "TRUSTED"
    UNTRUSTED = "UNTRUSTED"
    INTERNAL_ORIGIN = "INTERNAL_ORIGIN"
    EXTERNAL_ORIGIN = "EXTERNAL_ORIGIN"
    USER_PROVIDED = "USER_PROVIDED"
    TOOL_PROVIDED = "TOOL_PROVIDED"
    SUSPICIOUS_CONTROL_CONTENT = "SUSPICIOUS_CONTROL_CONTENT"

    EXECUTABLE_CONTENT = "EXECUTABLE_CONTENT"
    PERSISTENT_ARTIFACT = "PERSISTENT_ARTIFACT"
    CONFIGURATION = "CONFIGURATION"
    PRIVILEGED_CONTEXT = "PRIVILEGED_CONTEXT"
